server:
  port: 7201

# datasoure默认使用JDBC
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: toby1874
    password: 
    url: jdbc:mysql://127.0.0.1:3306/pig?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest 