server:
  port: 7902

# datasoure默认使用JDBC
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: '{cipher}cab983fb874e8d61dade49d09f30a6ffa5e61b5d546e696c6f99b59760b10905'
    password: '{cipher}cab983fb874e8d61dade49d09f30a6ffa5e61b5d546e696c6f99b59760b10905'
      
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: '{cipher}f68a421a7780ca020adde138a59e7085066e6283e71a2dfa223eccf22f0d00aa'
    url: jdbc:mysql://127.0.0.1:3306/mail?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
  redis:
      database: 9
      host: localhost
      port: 6379
      password:     # 密码（默认为空）
      timeout: 6000  # 连接超时时长（毫秒）
      pool:
          max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
          max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-idle: 10      # 连接池中的最大空闲连接
          min-idle: 5       # 连接池中的最小空闲连接 